### ISSUE TITLE
Causes issue with external apps calling contentctl

### ISSUE THREAD

**Issue by josehelps** [splunk/contentctl#171]
When using the API implementation this causes a hard fault. 
https://github.com/splunk/contentctl/blob/d94aa7ba488a9fa60c1b79faca11514f9392d712/contentctl/objects/abstract_security_content_objects/detection_abstract.py#L150

See error generated:

```
 File "/Users/jhernandez/Library/Caches/pypoetry/virtualenvs/site-gen-gDuMgKBR-py3.12/lib/python3.12/site-packages/contentctl/objects/abstract_security_content_objects/detection_abstract.py", line 150, in cve_enrichment
    raise Exception("CVE Enrichment Functionality not currently supported.  It will be re-added at a later time.")
Exception: CVE Enrichment Functionality not currently supported.  It will be re-added at a later time.
```

This was my implementation:

```
    config = load_config(security_content_path)
    
    try:
        director_output = validate_func(config)
        print(director_output)
```

**Comment by pyth0n1c** [comment]
Working on the fixes in the following branch: https://github.com/splunk/contentctl/pull/170

**Comment by josehelps** [comment]
tested and solved on this PR. https://github.com/splunk/contentctl/pull/170
