### ISSUE TITLE
Detection - known_false_positives should support a list

### ISSUE THREAD

**Issue by 0xC0FFEEEE** [splunk/contentctl#264]
Wasn't sure whether to raise this here or within security_content...

`known_false_positives` is currently of type str, which is fine if there is one known false positive, but more than one would just result in a blob of text that is difficult to read.

Ideally this field should support either a string or list of strings so multiple false positives can be added, providing improved readability and separation of distinct known false positives.

Appreciate this will require an update to the [ESCU savedsearch.conf spec](https://github.com/splunk/security_content/wiki/ESCU-%E2%80%90-savedsearch.conf-spec), but I don't believe it's used anywhere within Splunk today.

**Comment by ljstella** [comment]
`known_false_positives` is currently rendered in the Enterprise Security app, in the Use Case Library:
![Screenshot 2024-08-27 at 9 47 26 AM](https://github.com/user-attachments/assets/d47cb3a9-7533-4c97-8cba-c21693b752fe)

Even lengthy sections in an 80-character wide terminal look relatively small in this UI:
![Screenshot 2024-08-27 at 9 52 10 AM](https://github.com/user-attachments/assets/ce45f42d-8b94-4f93-8dfa-7bc37f62805a)

This is a UI surface our team doesn't own, and has its own limitations on formatting. If you'd like alternative formats to appear there in the UI, or for the field to be used in additional places in ES, it probably has to go through [Splunk Ideas](https://ideas.splunk.com/)

**Comment by 0xC0FFEEEE** [comment]
Thanks @ljstella, I thought I might have missed somewhere that field does appear.

This shares a gripe I have with some other text based fields in ES, so I might just ask for markdown support instead 😄
