### ISSUE TITLE
Detection - analytic story must exist in content pack

### ISSUE THREAD

**Issue by 0xC0FFEEEE** [splunk/contentctl#265]
I would like to adopt contentctl in a phased manner as we are a Splunk cloud customer and effectively replacing ESCU with our own forked content will take some effort and coordination (we have >950 ESCU rules enabled, many of which have been customized to some extent).

Phase 1 will entail deploying our own custom rules in a content pack, however those rules cannot reference an existing ESCU analytic story as it must exist in the content pack.

Ideally it should be possible to reference an analytic story (particularly as this is a required field) that is defined elsewhere, such as ESCU. Maybe through the use of a new config stanza (ideal as could be specified per-rule), or as a CLI flag to disable enforcement of the check that ensures the analytic story exists.

**Comment by ljstella** [comment]
I'd suggest porting the stories referenced by your detections to your own app. ES's UI can... _do some interesting things_ if you have analytics that reference stories that no longer exist- and creating a cross-app dependency like that would allow that to theoretically happen at any point in the future without you performing any updates to your own content, and in a fashion that is beyond the scope of existing testing suites we run.

Are you using stories in Risk Notable-generating searches, or for any specific use case beyond just "grouping similar analytics together"? If not, I'd recommend using your own and perhaps using them to apply groupings that make more sense with the content you have enabled. 

Also, while I don't believe `contentctl` enforces it today, I'd **highly** recommend putting a unique identifier in your own analytic story names. If I was doing this for ESCU, it would be `ESCU - ` at the beginning of the name like our detections, but something like `SOC - ` or `vSOC - ` or `GSOC -` depending on your org structure. Or your app abbreviation, or just your own initials. Given some of the _unique behaviors_ ES exhibits when displaying these, name collisions in stories could cause some serious pain that you can avoid by ensuring you add something unique to them.

**Comment by 0xC0FFEEEE** [comment]
Thanks @ljstella, that's a point I hadn't considered, though I was hoping to avoid duplicating ESCU content (albeit prefixed with something to differentiate them).

We use analytic stories primarily for grouping detections, but there is at least one custom RBA rule that uses them within the logic itself to trigger a risk notable when 3 distinct rules from a select group of stories have triggered.

I've now gone from not wanting to create duplicate content (largely born of laziness!), to needing to duplicate content to avoid breaking my precious rules because of something I hadn't considered before! 😬

Thanks again @ljstella 🥲
