### ISSUE TITLE
Add support for enabling individual detections

### ISSUE THREAD

**Issue by obpedro** [splunk/contentctl#55]
Currently, when `contentctl build` runs, all of the detections in the resulting savedsearches.conf file will have `disabled = true`. It would be great if we could enable individual detections, like by specifying `disabled: false` in a given detection's yaml file. Thanks!

**Comment by obpedro** [comment]
PR #60 opened to address this issue :)

**Comment by pyth0n1c** [comment]
Closing this issue as the feature was added in https://github.com/splunk/contentctl/pull/116
