### ISSUE TITLE
tests template folder missing

### ISSUE THREAD

**Issue by m0n3yspider** [splunk/contentctl#66]
contentctl init does not produce the tests folder which causes errors when running contentctl new -t detection

**Comment by pyth0n1c** [comment]
Great news! Thank you for reporting the issue and submitting the initial fix.
We have fixed this and improved functionality even more in the following PR and released to pip the fix in version 3.0.1 of contentctl :) 
https://github.com/splunk/contentctl/pull/96

Please see the following release, which contains the fix:
https://github.com/splunk/contentctl/releases/tag/v3.0.1
